/** Entradas del índice de la página Tutoriales (anclas `#${id}`). */
export const TUTORIALS_TOC: { id: string; label: string }[] = [
  { id: 'navegacion', label: 'Menú lateral y sesión' },
  { id: 'proyectos', label: 'Proyectos' },
  { id: 'workspace', label: 'Dentro de la obra (vista general)' },
  { id: 'detalles', label: 'Pestaña Detalles' },
  { id: 'flujo', label: 'Pestaña Flujo' },
  { id: 'archivos', label: 'Pestaña Archivos' },
  { id: 'entrega-planos', label: 'Pestaña Entrega planos' },
  { id: 'revisiones', label: 'Pestaña Revisiones' },
  { id: 'especificaciones', label: 'Pestaña Especificaciones' },
  { id: 'presupuesto', label: 'Pestaña Presupuesto' },
  { id: 'eventos', label: 'Pestaña Eventos' },
  { id: 'pliegos', label: 'Pestaña Pliegos' },
  { id: 'materiales', label: 'Pestaña Materiales' },
  { id: 'config-proyecto', label: 'Configuración del proyecto' },
  { id: 'tablero', label: 'Tablero de tareas' },
  { id: 'chat', label: 'Chat interno' },
  { id: 'avisos', label: 'Avisos y notificaciones' },
  { id: 'admin', label: 'Usuarios (solo dirección)' },
]
